name: QuestPlugin
main: com.woxloi.questplugin.QuestPlugin
version: 2.2
api-version: 1.19
depend: [MythicMobs]
softdepend: [Vault]
website: https://github.com/woxlo1/QuestPlugin
authors:
  - woxloi
commands:
  quest:
    description: クエストシステム